### ISSUE TITLE
RTCWHQ.py does not run

### ISSUE THREAD

**Issue by nikich340** [Krischan74/RTCWHQ#4]
The rtcwhq.py gives errors in imported modules and program does not work. Win10 x64, CUDA 10.1, pytorch 1.1.0. Any ideas how to solve it?
Tested original ESRGAN neuronet, works well.

```
>python rtcwhq.py input 8 2048 2 2.0 0.0 4 90
======================================================================
RTCWHQ batch upscaling with ERSGAN started
======================================================================
Model:           models/cartoonpainted_400000.pth
Fontmodel:       models/ReducedColorsAttempt.pth
Folder:          input
Maximum scaling: 8x
Maximum size:    2048 Pixel
Gaussian Blur:   2 Pixel
Contrast:        200%
Brightness:      0%
Sharpen:         4 Pixel
JPEG Quality:    90
----------------------------------------------------------------------
Found 4 images: 0 PNG, 2 TGA and 2 JPEG
----------------------------------------------------------------------
Puny human is instructed to wait until the models are been prepared...
Traceback (most recent call last):
  File "rtcwhq.py", line 179, in <module>
    model.load_state_dict(torch.load(model_path), strict=True)
  File "C:\Program Files\Python37\lib\site-packages\torch\serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\Program Files\Python37\lib\site-packages\torch\serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by nikich340** [comment]
Solution: download archive from here https://github.com/Krischan74/RTCWHQ/issues/3
